name: Deploy to ECS with CodeDeploy via ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      CODEDEPLOY_DEPLOYMENT_GROUP: "frontend-deploy-group"
      CODE_DEPLOY_APPLICATION: "frontend-deploy"
      ECR_REGISTRY: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com"
      ECR_REPOSITORY: "frontend-app"
      ECS_CLUSTER_NAME: "application_cluster"
      ECS_SERVICE_NAME: "frontend"
      IMAGE_TAG: ${{ github.sha }}
      S3_BUCKET: "deployment-bckt-europe"
      TASK_DEFINITION_ARN: arn:aws:ecs:eu-north-1:038462779186:task-definition/frontend-task:12

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

    - name: Build Docker image
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

    - name: Tag Docker image
      run: |
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Push Docker image to Amazon ECR
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Update AppSpec with Task Definition ARN
      run: |
        echo "
        version: 0.0
        Resources:
          - TargetService:
              Type: AWS::ECS::Service
              Properties:
                TaskDefinition: arn:aws:ecs:eu-north-1:038462779186:task-definition/frontend-task:12
                LoadBalancerInfo:
                  ContainerName: app
                  ContainerPort: 80
        " > appspec.yaml

    - name: Upload AppSpec file to S3
      run: |
        aws s3 cp appspec.yaml s3://${{ env.S3_BUCKET }}/appspec.yaml --region us-west-2

    - name: Create Deployment
      id: create_deployment
      run: |
        DEPLOYMENT_ID=$(aws deploy create-deployment \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION }} \
          --deployment-group-name ${{ env.CODEDEPLOY_DEPLOYMENT_GROUP }} \
          --revision "{\"revisionType\": \"S3\", \"s3Location\": {\"bucket\": \"${{ env.S3_BUCKET }}\", \"key\": \"appspec.yaml\", \"bundleType\": \"YAML\"}}" \
          --region eu-north-1 \
          --query 'deploymentId' \
          --output text)
        echo "Deployment ID: $DEPLOYMENT_ID"
        echo "deployment_id=$DEPLOYMENT_ID" >> $GITHUB_OUTPUT

    - name: Wait for Deployment Completion
      run: |
        aws deploy wait deployment-successful \
          --deployment-id ${{ steps.create_deployment.outputs.deployment_id }} \
          --region eu-north-1
